2021-07-01 11:16:13,517:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:16:24,626:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:16:35,268:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:16:45,715:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 11:16:45,718:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:16:56,366:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:17:06,649:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:17:13,554:	ERROR:	Mqtt.py:_connect():81	Exception in connect to mqtt: timed out
2021-07-01 11:17:17,096:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:17:18,825:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "GROUP",
  "DATA": {
    "GROUP_ID": "b9bc79b8-cdc5-44a7-be95-78c3341791cb",
    "PROPERTIES": [
      {
        "ID": 0,
        "VALUE": 1
      }
    ]
  }
}
2021-07-01 11:17:18,825:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:19,026:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:19,026:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:19,227:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:19,227:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:19,428:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:19,428:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:19,528:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:19,528:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:19,729:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:19,730:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:20,131:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:20,131:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:20,733:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:20,733:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:21,135:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:21,135:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:21,536:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:21,536:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:21,938:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:21,938:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:22,139:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:22,139:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:24,848:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:24,849:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:25,150:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:25,150:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:25,250:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:25,250:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:25,552:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:25,552:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:25,652:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:25,652:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:25,953:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:25,953:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:26,355:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:26,355:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:26,556:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:26,556:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:26,857:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:26,858:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:26,958:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:26,958:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:27,260:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:27,260:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:27,549:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:17:27,663:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {"CMD":"DEVICE","DATA":{"DEVICE_ID":"268f9df6-95df-c43c-bf52-bb4b2dac442e","PROPERTIES":[{"ID":0,"VALUE":1},{"ID":1,"VALUE":100},{"ID":2,"VALUE":29}]}}
2021-07-01 11:17:27,663:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 11:17:27,748:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:17:27,749:	INFO:	Hc.py:__hcUpdateReconnectStToDb():103	Update cloud reconnect status to db
2021-07-01 11:19:55,579:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:19:56,875:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:20:06,877:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:20:07,508:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:20:17,508:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:20:17,815:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:20:27,817:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:20:28,616:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:20:38,618:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:20:41,252:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:20:51,254:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:20:59,664:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:21:56,438:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:21:58,158:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:22:08,159:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:22:10,131:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:22:20,132:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:22:20,528:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:22:30,529:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:22:31,455:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:22:41,456:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:22:41,867:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:22:51,868:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:22:52,672:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:23:26,095:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:23:36,102:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:23:46,105:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:23:56,107:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 11:23:56,158:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:24:06,161:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:24:16,163:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:24:26,165:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:24:36,168:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:24:37,310:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: { "CMD":"HC_CONNECT_TO_CLOUD", "DATA":{ "END_USER_PROFILE_ID":10103,"REFRESH_TOKEN":"OGj2Lo8elXRxCiOit9i2lmZlHlOqA5KCoQ8NEAkmcU94F8zMFmpED3SQzd7OJDOvkJd0yWBPjP32y6fuSCvJCXlCbvWVrktDWe67YvMcjHnZCzOR1mu3+c6lKNGHWvfvtDLJTpWZQIyWYqx/+l3agx0ULYckAvV5K3gKfgVNem/JOP57IVEWLdSdMwuMIQwIDh0MgUiqpbFEse0kVWPr1T9CChTerHDDn5sMBvWh4ug="}}
2021-07-01 11:27:38,086:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:28:40,517:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:28:41,364:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:28:56,530:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:28:58,846:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 11:29:24,676:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 11:29:26,157:	ERROR:	Signalr.py:ReConnect():97	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:31:55,604:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:32:06,839:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:32:18,621:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:32:31,545:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:33:02,600:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:33:03,597:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:33:08,601:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:33:13,608:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:33:13,634:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:33:18,612:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:33:23,616:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:33:23,638:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:33:28,621:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:33:33,628:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:33:33,641:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():111	Update cloud disconnect status to db
2021-07-01 12:36:05,652:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:36:06,647:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:36:11,651:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:36:15,660:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:36:16,659:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:36:21,664:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:36:25,664:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:36:26,668:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:36:31,676:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:36:35,668:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():111	Update cloud disconnect status to db
2021-07-01 12:36:35,695:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:36:36,680:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:40:48,730:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:40:49,732:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:40:54,738:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:40:58,737:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:40:59,741:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:41:04,748:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:41:08,741:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:41:09,756:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:41:14,760:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:41:18,745:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 12:41:18,794:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:41:19,768:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:45:33,495:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:45:34,481:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:45:39,486:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:45:44,492:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:45:49,502:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:45:54,512:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:45:59,523:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:04,534:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:06,429:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:46:07,424:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:12,430:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:17,436:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:21,437:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:46:22,447:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:27,455:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:32,469:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:36,446:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:46:37,478:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:42,491:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:47,497:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:51,450:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 12:46:51,494:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:46:52,507:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:46:57,517:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:47:02,530:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:47:06,500:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:47:07,537:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:47:12,546:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:47:17,559:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:47:21,506:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:47:23,702:	INFO:	Hc.py:__hcUpdateReconnectStToDb():103	Update cloud reconnect status to db
2021-07-01 12:51:56,379:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:51:57,376:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:52:02,385:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:52:07,398:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:52:11,395:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:52:12,412:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:52:17,424:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:52:22,438:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:52:26,402:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:52:27,451:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:52:32,463:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:52:37,475:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:52:41,412:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 12:52:41,453:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:52:42,487:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 12:58:18,276:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:58:18,280:	ERROR:	Signalr.py:DisConnect():72	Exception when disconnect with signalr server: 'Signalr' object has no attribute '_Signalr__hub'
2021-07-01 12:58:49,720:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:58:49,724:	ERROR:	Signalr.py:DisConnect():72	Exception when disconnect with signalr server: 'Signalr' object has no attribute '_Signalr__hub'
2021-07-01 12:59:21,395:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 12:59:21,398:	ERROR:	Signalr.py:DisConnect():72	Exception when disconnect with signalr server: 'Signalr' object has no attribute '_Signalr__hub'
2021-07-01 13:01:10,413:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:01:10,417:	ERROR:	Signalr.py:DisConnect():72	Exception when disconnect with signalr server: 'Signalr' object has no attribute '_Signalr__hub'
2021-07-01 13:04:28,490:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:04:29,495:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:06:49,504:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:06:50,507:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:06:55,518:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:00,527:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:04,512:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:07:05,539:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:10,549:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:15,560:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:19,522:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:07:20,570:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:25,580:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:30,588:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:34,533:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 13:07:34,535:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:07:35,598:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:40,611:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:45,624:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:49,558:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:07:50,637:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:07:55,650:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:07,513:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:08:08,512:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:13,521:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:18,530:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:22,520:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:08:23,542:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:28,555:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:33,564:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:37,533:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:08:38,573:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:43,586:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:48,593:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:52,537:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 13:08:52,543:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:08:53,603:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:08:58,610:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:03,622:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:07,587:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:09:08,634:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:13,645:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:18,658:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:22,597:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:09:23,670:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:28,682:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:33,695:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:37,607:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:09:38,706:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:43,715:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:48,726:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:52,617:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:09:53,738:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:09:58,751:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:10:03,761:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:10:07,626:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:12:42,663:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:12:43,665:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:12:48,672:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:12:53,682:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:12:57,671:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:12:58,695:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:13:03,705:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:13:08,717:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:13:12,681:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:13:13,726:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:13:18,733:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:13:23,744:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:13:27,691:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 13:13:27,696:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:13:28,755:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:13:33,766:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:13:38,779:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:14:59,928:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:15:00,930:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:05,941:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:10,954:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:14,937:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:15:15,965:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:20,971:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:25,981:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:29,946:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:15:30,993:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:36,006:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:41,017:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:44,950:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 13:15:44,955:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:15:46,031:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:15:51,046:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:20:31,859:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:20:32,815:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:20:37,830:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:20:42,845:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:20:46,891:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:20:47,855:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:20:52,870:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:20:57,882:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:21:01,898:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:21:02,890:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:21:07,898:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:21:12,907:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:21:16,907:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 13:21:16,910:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:21:17,915:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:02,166:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:22:03,159:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:08,163:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:13,168:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:17,175:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:22:18,172:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:23,176:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:28,181:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:32,178:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:22:33,190:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:38,197:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:43,205:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:47,182:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 13:22:47,184:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:22:48,212:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:22:53,217:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:23:26,759:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:23:27,748:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:23:32,753:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:23:37,760:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:23:41,768:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:23:42,764:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:24:24,392:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:24:25,385:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:24:30,389:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:24:35,396:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:24:39,402:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:24:40,406:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:24:45,412:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:24:50,417:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:24:54,406:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:24:55,424:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:00,432:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:05,436:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:09,410:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 13:25:09,467:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:25:10,440:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:15,444:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:20,449:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:24,475:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:25:25,457:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:30,465:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:35,473:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:39,480:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:25:40,480:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:45,484:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:50,488:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:25:54,484:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:25:55,492:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:00,497:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:05,504:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:09,489:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:26:10,512:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:15,516:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:20,524:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:24,492:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:26:25,532:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:30,540:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:35,544:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:39,497:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:26:40,550:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:45,556:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:50,561:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:26:54,500:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:26:55,568:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:00,572:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:05,580:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:09,504:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:27:10,584:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:15,592:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:20,596:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:24,509:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:27:25,600:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:27,851:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:27:28,842:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:33,851:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:38,859:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:42,862:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:27:43,864:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:48,868:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:53,875:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:27:57,866:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:27:58,880:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:03,885:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:08,893:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:12,870:	INFO:	Hc.py:__hcUpdateDisconnectStToDb():113	Update cloud disconnect status to db
2021-07-01 13:28:12,873:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:28:13,900:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:18,905:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:23,914:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:27,906:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:28:28,922:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:33,928:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:38,934:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:42,909:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:28:43,940:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:48,945:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:53,952:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:28:57,915:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:28:58,958:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:29:03,966:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:29:08,973:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:29:12,918:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:29:13,981:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:29:18,988:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:29:23,993:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:29:27,923:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:29:30,516:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:29:35,520:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:29:40,525:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:29:45,519:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:29:45,535:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 13:30:00,524:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 13:30:02,582:	INFO:	Hc.py:__hcUpdateReconnectStToDb():103	Update cloud reconnect status to db
2021-07-01 13:30:17,593:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 16:49:47,248:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 16:50:02,692:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 16:50:44,354:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 16:50:55,456:	DEBUG:	Hc.py:__signalrItemHandler():205	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:50:55,459:	DEBUG:	Hc.py:__signalrHandlerCommand():224	Forward data to mqtt
2021-07-01 16:50:55,460:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:50:55,461:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 16:50:55,561:	DEBUG:	Hc.py:__signalrItemHandler():205	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:50:55,561:	DEBUG:	Hc.py:__signalrHandlerCommand():224	Forward data to mqtt
2021-07-01 16:50:55,663:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:50:55,663:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 16:50:59,820:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 16:51:00,426:	DEBUG:	Hc.py:__signalrItemHandler():205	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:51:00,427:	DEBUG:	Hc.py:__signalrHandlerCommand():224	Forward data to mqtt
2021-07-01 16:51:00,428:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:51:00,430:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 16:51:00,529:	DEBUG:	Hc.py:__signalrItemHandler():205	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:51:00,531:	DEBUG:	Hc.py:__signalrHandlerCommand():224	Forward data to mqtt
2021-07-01 16:51:00,535:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:51:00,535:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 16:51:00,639:	DEBUG:	Hc.py:__signalrItemHandler():205	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:51:00,640:	DEBUG:	Hc.py:__signalrHandlerCommand():224	Forward data to mqtt
2021-07-01 16:51:00,741:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 16:51:00,742:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():188	mqtt data receiver invalid
2021-07-01 17:00:42,772:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:00:42,877:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "STOP"
}
2021-07-01 17:00:42,877:	ERROR:	Hc.py:__mqttHandlerTopicHcControl():167	mqtt data receiver invalid
2021-07-01 17:00:58,287:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:01:13,610:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:01:29,044:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:01:44,406:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:01:59,704:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:02:15,027:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:02:31,493:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:02:47,134:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:03:04,658:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:03:04,759:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "STOP"
}
2021-07-01 17:03:04,760:	ERROR:	Hc.py:__mqttHandlerTopicHcControl():167	mqtt data receiver invalid
2021-07-01 17:03:21,055:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:03:32,120:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "DEVICE_UPDATE",
  "TIME_UPDATE": "1970 01 01 00:00"
}
2021-07-01 17:03:32,128:	ERROR:	Hc.py:__mqttHandlerTopicHcControl():167	mqtt data receiver invalid
2021-07-01 17:03:32,229:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "HC_CONNECT_TO_CLOUD",
  "DATA": {
    "END_USER_PROFILE_ID": 10059,
    "REFRESH_TOKEN": "10a8F5yStJ1A7JBXRzc4NZuRhYKT691L1d+mBFszYUVWwpqYNgn2K7NB+dYWX4t20JKZwIF1HBUEf7EdwOQLAN1k9qNTGR5opGD1xQSdiaZKWc0kSiYZJ0PsgzqK/zfp5Wk7zeUwCkEpBlHeBRQ3J62wSfNmONDC4rps+WHk7+5A9qnCfs2Mo5f5bkFFoSC2vrDiBPInTuXXPwzItNUjBHKhmnoBRrcOd2xEsTAy/b8ZWMomutAjMBpJc9KM3Ipp"
  }
}
2021-07-01 17:03:36,779:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:03:52,514:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:04:09,583:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:04:27,317:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:04:42,895:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:04:58,217:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:05:13,500:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:05:28,781:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:05:44,111:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:05:59,530:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:06:14,979:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:06:30,272:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:06:45,535:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:07:00,810:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:07:16,207:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:07:31,487:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:07:46,776:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:08:02,205:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:08:17,543:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:08:20,178:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:08:20,281:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "HC_CONNECT_TO_CLOUD",
  "DATA": {
    "END_USER_PROFILE_ID": 10059,
    "REFRESH_TOKEN": "10a8F5yStJ1A7JBXRzc4NZuRhYKT691L1d+mBFszYUVWwpqYNgn2K7NB+dYWX4t20JKZwIF1HBUEf7EdwOQLAN1k9qNTGR5opGD1xQSdiaZKWc0kSiYZJ0PsgzqK/zfp5Wk7zeUwCkEpBlHeBRQ3J62wSfNmONDC4rps+WHk7+5A9qnCfs2Mo5f5bkFFoSC2vrDiBPInTuXXPwzItNUjBHKhmnoBRrcOd2xEsTAy/b8ZWMomutAjMBpJc9KM3Ipp"
  }
}
2021-07-01 17:08:32,935:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:08:35,558:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:08:48,206:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:08:50,891:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:08:52,462:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "GROUP",
  "DATA": {
    "GROUP_ID": "6b439a0e-ac62-417a-9c8e-7cfb24e34deb",
    "PROPERTIES": [
      {
        "ID": 0,
        "VALUE": 1
      }
    ]
  }
}
2021-07-01 17:08:52,463:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():189	mqtt data receiver invalid
2021-07-01 17:08:52,510:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "GROUP",
  "DATA": {
    "GROUP_ID": "6b439a0e-ac62-417a-9c8e-7cfb24e34deb",
    "PROPERTIES": [
      {
        "ID": 0,
        "VALUE": 1
      }
    ]
  }
}
2021-07-01 17:08:52,510:	ERROR:	Hc.py:__mqttHandlerCmdConnectToCloud():189	mqtt data receiver invalid
2021-07-01 17:09:03,547:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:09:06,206:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:09:10,218:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "DEVICE_UPDATE",
  "TIME_UPDATE": "1970 01 01 00:00"
}
2021-07-01 17:09:10,219:	ERROR:	Hc.py:__mqttHandlerTopicHcControl():167	mqtt data receiver invalid
2021-07-01 17:09:10,319:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "HC_CONNECT_TO_CLOUD",
  "DATA": {
    "END_USER_PROFILE_ID": 10117,
    "REFRESH_TOKEN": "OGj2Lo8elXRxCiOit9i2ljgHL7O1DAg8P8uSg/HQcky35qqiSOfGaBSbold8qNfhBNPTpw4m+8vLE4a6ObgqkkmJALfXdR657/9UEtOdihJQX40jzCMlKhs1pkxAxBExuj+HLN3Wom12csqrodgidt3wEd42NwKxnWu9Jj+UCsxVmkqgAUWifdxWK3omDOOVupfxNOgQ5VxGwwaA6via9Id0/h29E/8HTlaKPa+fYPHBTEIWGDUa2cpfDGbdaCGB"
  }
}
2021-07-01 17:09:18,995:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:09:34,284:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:09:50,326:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:10:10,265:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:10:10,367:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "HC_CONNECT_TO_CLOUD",
  "DATA": {
    "END_USER_PROFILE_ID": 10117,
    "REFRESH_TOKEN": "OGj2Lo8elXRxCiOit9i2ljgHL7O1DAg8P8uSg/HQcky35qqiSOfGaBSbold8qNfhBNPTpw4m+8vLE4a6ObgqkkmJALfXdR657/9UEtOdihJQX40jzCMlKhs1pkxAxBExuj+HLN3Wom12csqrodgidt3wEd42NwKxnWu9Jj+UCsxVmkqgAUWifdxWK3omDOOVupfxNOgQ5VxGwwaA6via9Id0/h29E/8HTlaKPa+fYPHBTEIWGDUa2cpfDGbdaCGB"
  }
}
2021-07-01 17:10:25,730:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:10:41,021:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:10:56,578:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:11:11,867:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:11:27,169:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:11:42,376:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:11:57,601:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:12:12,854:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:12:21,644:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "DEVICE_UPDATE",
  "TIME_UPDATE": "1970 01 01 00:00"
}
2021-07-01 17:12:21,645:	ERROR:	Hc.py:__mqttHandlerTopicHcControl():167	mqtt data receiver invalid
2021-07-01 17:12:21,745:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "HC_CONNECT_TO_CLOUD",
  "DATA": {
    "END_USER_PROFILE_ID": 10059,
    "REFRESH_TOKEN": "10a8F5yStJ1A7JBXRzc4NZuRhYKT691L1d+mBFszYUVWwpqYNgn2K7NB+dYWX4t20JKZwIF1HBUEf7EdwOQLAN1k9qNTGR5opGD1xQSdiaZKWc0kSiYZJ0PsgzqK/zfpcVFIXs/OFZbcnkqjGi+XEECbJI1be61k+mznf7cVpghFWmlH4apfwqtFszQavEIdtJIR+UXFQRHe07K/shBuraAFdMALIbew5b0WgQJHxU1GmzSK3mu/ourHldcSoVVt"
  }
}
2021-07-01 17:12:28,122:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:12:43,487:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:12:59,506:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:13:14,773:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:13:30,054:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:13:45,389:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:14:00,687:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:14:15,072:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "DEVICE_UPDATE",
  "TIME_UPDATE": "1970 01 01 00:00"
}
2021-07-01 17:14:15,072:	ERROR:	Hc.py:__mqttHandlerTopicHcControl():167	mqtt data receiver invalid
2021-07-01 17:14:15,172:	DEBUG:	Hc.py:__mqttHandlerTopicHcControl():154	mqtt data receive from topic HC.CONTROL: {
  "CMD": "HC_CONNECT_TO_CLOUD",
  "DATA": {
    "END_USER_PROFILE_ID": 10058,
    "REFRESH_TOKEN": "10a8F5yStJ1A7JBXRzc4Nd4LpNGZZmRO8ayikBRBVnZvhkff3B6cPcRs5HDQMKB6htzQjWsvy7xnw1nKrV2xhJcrUKF79IqzTAIBDolLDsLmLokBEr93cCKgXIDi3Wxi+Y+MIC22nDC8qy5vYBLz4188xUNq0PEjUZuf7d1RX68AzZNdhBl26nvGUyY7jqCFjsZtPtR/Ds8QqUvLawWPY9zwImc4OuDoJygG+M8sD0xEXBXgwXwTb/GFKnTCsRIt"
  }
}
2021-07-01 17:14:15,932:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:14:31,296:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 17:14:46,630:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:33:30,958:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:36:12,142:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:36:27,754:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:36:43,215:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:36:58,574:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:37:12,190:	ERROR:	Mqtt.py:_connect():81	Exception in connect to mqtt: timed out
2021-07-01 20:37:12,801:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:12,802:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:37:14,129:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:37:17,762:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:17,762:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:37:22,690:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:22,691:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:37:27,718:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:27,719:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:37:29,544:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:37:32,715:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:32,716:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:37:37,742:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:37,743:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:37:42,769:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:42,770:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:37:45,001:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:37:47,673:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:47,674:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:37:52,800:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:52,801:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:37:57,726:	DEBUG:	Hc.py:__signalrItemHandler():206	handler receive signal data in Command is {
    "CMD": "EVENT_TRIGGER",
    "DATA":
    {
        "EVENT_TRIGGER_ID": "aa3549d4-5471-4d75-b0b2- b70fa5c10fb2"
    }
}
2021-07-01 20:37:57,726:	DEBUG:	Hc.py:__signalrHandlerCommand():228	Forward data to mqtt
2021-07-01 20:38:01,757:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:38:19,069:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:38:43,496:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:39:03,276:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:39:34,110:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:40:36,920:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:40:52,247:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:41:59,859:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:42:12,904:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:42:46,096:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:43:02,485:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:43:18,611:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:45:42,159:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:46:39,392:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:46:53,507:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:47:45,744:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:51:10,926:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:51:26,663:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:51:55,874:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:52:58,539:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:52:58,848:	ERROR:	Signalr.py:ReConnect():101	Exception when connect with signalr server: 'Signalr' object has no attribute '_Signalr__hub'
2021-07-01 20:53:13,850:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:53:14,367:	ERROR:	Signalr.py:ReConnect():101	Exception when connect with signalr server: 'Signalr' object has no attribute '_Signalr__hub'
2021-07-01 20:53:29,368:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:53:29,587:	ERROR:	Signalr.py:ReConnect():101	Exception when connect with signalr server: 'Signalr' object has no attribute '_Signalr__hub'
2021-07-01 20:53:44,590:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:53:45,081:	ERROR:	Signalr.py:ReConnect():101	Exception when connect with signalr server: 'Signalr' object has no attribute '_Signalr__hub'
2021-07-01 20:53:58,586:	ERROR:	Mqtt.py:_connect():81	Exception in connect to mqtt: timed out
2021-07-01 20:54:00,083:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:56:49,070:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:56:49,493:	ERROR:	Signalr.py:ReConnect():100	Exception when connect with signalr server: 'Signalr' object has no attribute '_Signalr__hub'
2021-07-01 20:57:33,245:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:57:33,542:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-01 20:57:53,840:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-01 20:57:53,916:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
2021-07-02 09:53:37,340:	INFO:	Hc.py:__HcCheckConnectWithCloud():46	Hc send heardbeat to cloud
2021-07-02 09:53:37,707:	ERROR:	Signalr.py:__startConnect():56	Exception when connect with signalr server: can only concatenate str (not "NoneType") to str
